[package]
name = "sbd-server-test-suite"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
sbd-client = { version = "0.0.1-alpha", path = "../sbd-client" }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = [ "full" ] }
