[package]
name = "sbd-server"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
anstyle = "1.0.6"
base64 = "0.22.0"
bytes = "1.6.0"
clap = { version = "4.5.4", features = [ "color", "derive", "wrap_help" ] }
ed25519-dalek = { version = "2.1.1", default-features = false }
rand = "0.8.5"
tokio = { version = "1.37.0", features = [ "full" ] }

# feature tungstenite
futures = { version = "0.3.30", optional = true }
tokio-tungstenite = { version = "0.21.0", default-features = false, features = [ "handshake" ], optional = true }

# feature fastwebsockets
fastwebsockets = { version = "0.7.1", features = [ "upgrade" ], optional = true }
http-body-util = { version = "0.1.0", optional = true }
hyper-util = { version = "0.1.3", features = [ "tokio" ], optional = true }
hyper = { version = "1.2.0", features = ["http1", "server"], optional = true }

[dev-dependencies]
escargot = { version = "0.5.10", features = [ "print" ] }
rcgen = "0.13.1"
sbd-client = { version = "0.0.1-alpha", path = "../sbd-client" }
serde_json = "1.0.116"
tempfile = "3.10.1"

[features]
default = [ "tungstenite" ]

tungstenite = [ "dep:futures", "dep:tokio-tungstenite" ]

fastwebsockets = [
  "dep:fastwebsockets",
  "dep:http-body-util",
  "dep:hyper-util",
  "dep:hyper",
]
