name = "tx5-signal-cf"
main = "src/index.ts"
compatibility_date = "2024-06-18"

[[durable_objects.bindings]]
name = "SIGNAL"
class_name = "DoSignal"

[[durable_objects.bindings]]
name = "RATE_LIMIT"
class_name = "DoRateLimit"

[[migrations]]
tag = "v1"
new_classes = ["DoSignal", "DoRateLimit"]
