name = "sbd"
main = "src/index.ts"
compatibility_date = "2024-06-03"
route = "sbd.holo.host/*"
account_id = "18ff2b4e6205b938652998cfca0d8cff"
minify = true
workers_dev = false

#[limits]
#cpu_ms = 5000

kv_namespaces = [
  { binding = "SBD_COORDINATION", id = "cde857dd4ea745fea55f80daa52a6d5c" }
]

[[durable_objects.bindings]]
name = "SIGNAL"
class_name = "DoSignal"

[[durable_objects.bindings]]
name = "RATE_LIMIT"
class_name = "DoRateLimit"

[[migrations]]
tag = "v1"
new_classes = ["DoSignal", "DoRateLimit"]
