[package]
name = "sbd-o-bahn-client-tester"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
hex = "0.4.3"
sbd-server = { workspace = true }
tokio = { version = "1.37.0", features = [ "full" ] }
