[package]
name = "sbd-o-bahn-server-tester"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
sbd-client = { workspace = true }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = [ "full" ] }
