[package]
name = "sbd-bench"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
base64 = "0.22.0"
sbd-server = { workspace = true }
sbd-client = { workspace = true, features = [ "raw_client" ] }
tokio = { version = "1.37.0", features = [ "full" ] }

[dev-dependencies]
criterion = { version = "0.5.1", features = [ "async_tokio" ] }

[[bench]]
name = "thru"
harness = false
