name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install vcpkg Packages
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          triplet: x64-windows-release
          token: ${{ github.token }}
          manifest-dir: ${{ github.workspace }}/.github/manifest
          github-binarycache: true

      - name: Cargo Test Windows
        if: matrix.os == 'windows-latest'
        env:
          RUST_BACKTRACE: 1
        run: |-
          $env:SODIUM_LIB_DIR="$(pwd)\vcpkg\packages\libsodium_x64-windows-release\lib"
          cargo build --all-targets && cargo test -- --nocapture

      - name: Cargo Test
        if: matrix.os != 'windows-latest'
        env:
          RUST_BACKTRACE: 1
        run: cargo build --all-targets && cargo test -- --nocapture
